### ISSUE TITLE
Not an issue: Congrats

### ISSUE THREAD

**Issue by orefalo** [ralphhanna/bpmn-server#1]
Neat piece of logic and very nice full featured UIs.

If I may,
- what is the roadmap for this project?
- How does it relate to https://github.com/paed01/bpmn-engine

Sincerely

**Comment by ralphhanna** [comment]
Hi, thanks for you kind words,

- Roadmap: continue to develop and enhance to become best of class in open source BPMN, a new release is coming very soon.
-Relation to bpmn-engine;  it  started as a layer in top of bpmn-engine, but then,.. it became a total re-write make use of Typescript and cleaner architecture. 
Thanks

**Comment by orefalo** [comment]
Tks
