### ISSUE TITLE
Passing output values to other tasks

### ISSUE THREAD

**Issue by mramin2000** [ralphhanna/bpmn-server#107]
Hello @ralphhanna ,

I'm using the bpmn-server for a student project. At the moment I'm trying to use a Service Task to compute an output value. This is done by a service that I have added to the MyServices Class in appDelegate.ts. Calling this method with the execution of the Service Task works fine. In the next step I like to pass the output value to another task. For testing I tried to use a Script or a Service Task. But in both cases I could not use the output value of the first service task as an input parameter. 

I'm not sure if this idea in general works. Are there best practices on how to pass output values from one task as input parameters to another task?

Thanks for the help!

**Comment by ralphhanna** [comment]
Hi,

You can capture output parameter into instance data by having a end trigger
```
data.result2=output;

```
![image](https://github.com/ralphhanna/bpmn-server/assets/11893416/1cc5dfb8-77ac-4dac-a13d-85bd02748516)

Then you can set input by having a start trigger:
```
 input.var1=data.result2;

``
