### ISSUE TITLE
`endedAt` for Boundary Events

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#113]
Hi @ralphhanna 

**Issue:**
`endedAt` for a Boundary Event is `null` instead of the actual end date & time after it's execution.

**Expected Behaviour:**
`endedAt` should have an actual end date & time after it gets executed

**Actual Behaviour:**
`endedAt`  is `null` after it gets executed

Example:
![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/2a600442-ad02-43e6-a697-be500a22da39)

Here, you can see the boundary timers get executed. But their `endedAt` value for the items are `null` in MongoDB.

But, in the other case
![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/7f4e0086-701a-4a5a-a251-d72c20e53a85)

Here the boundary timers are not executed or cancelled. In this case, `endedAt` values for the items have actual date & time.

Could you please look into this?

Thank you.

**Comment by ralphhanna** [comment]
Fixed in release 1.3.28

![image](https://github.com/ralphhanna/bpmn-server/assets/11893416/9d5ddc87-3109-4130-8e66-f1183de29db3)

- Item 4 & 5 : were executed and ended -with end timestamp
- Item 6: was executed - but cancelled - without timestamp

**Comment by ralphhanna** [comment]
Thanks

**Comment by MaheshkumarSundaram** [comment]
Thank you @ralphhanna
