### ISSUE TITLE
how to define target user and group of user in user task

### ISSUE THREAD

**Issue by kstan79** [ralphhanna/bpmn-server#114]
I'm try to use the webUI create service task however I cant figure up the way to define target user/group and seems no documentation explain how to do that, is it require camunda modeler?

**Comment by ralphhanna** [comment]
Documentation is coming soon.

**Comment by kstan79** [comment]
after some research i notice that we can capture camunda assignee property by adding more type in moddle option. i'd add some for user task which is userful and had apply PR #117 .

Technically it seems can capture xml property in json, however I dont know how to save it into mongodb instance. Hope your side can implement it.

Modified moddle
![moddle](https://github.com/ralphhanna/bpmn-server/assets/1889979/10729b57-7cfb-471c-88ca-e34b076c5538)

xml pasrsed successfully in definations
![loaded](https://github.com/ralphhanna/bpmn-server/assets/1889979/b8aeab8d-b03f-4957-9e54-7b304db3acd0)
![definations](https://github.com/ralphhanna/bpmn-server/assets/1889979/7e08b1e7-b98a-48b8-ae65-765c38311f48)

if the assignee's properties can save into user task (in instance collection), then I think is enough for basic implementation of user task in production.

**Comment by kstan79** [comment]
I'm manage to store bpmn user assignments into mongodb. Im using  camunda:assignee setting, the bpmn editor obtain from vscode extension list.

![method2c](https://github.com/ralphhanna/bpmn-server/assets/1889979/794a19d0-d7b9-44f2-8b7e-3c1293c9d92d)

the code i changed is `src/engine/Item.ts`:
[
![method2a](https://github.com/ralphhanna/bpmn-server/assets/1889979/142f9e13-704f-4b45-ab68-9c8483f83b4d)
](url)

you can see below is the result obtain from `dataStore.findItems()`
![method2](https://github.com/ralphhanna/bpmn-server/assets/1889979/34771a77-dcb9-4132-8123-24c417c2bb9d)
we can search using below way
```typescript
items = await this.bpmnServer.dataStore.findItems( { "items.assignments.assignee":'benjamin' })
```

Kindly advise whether above approach approve, or need another way to implement it, I will send another PR after you approve

**Comment by ralphhanna** [comment]
Thanks for all your help, but please consider my initial design as follows:

# Access Rules

```json
   [
    { Authorize: {group:'public', toPerform: 'Execute', on: 'start'}},
    { Designate: {user: currentUser, as : 'Owner'} , 
        at:{ element: 'start', event:'start'}},
    { Authorize: {actor:'Owner', toPerform: 'Execute', on: ['Buy','Drive'],}},
    { Assign: {group:'Cleaners', toPerform: 'Execute', on:'Clean',}},
    { Assign: {group:'Mechanics', toPerform: 'Execute', on:'Repair',}},
    { Notify: {actor:'Owner'   },
        at: {element: 'Drive', event:' start'}
        delayed: { min: 15 , cancelOn: 'end' }
   ]
```

**Authorize** is evaluated on request:

	- isAuthorized(user,action,object): true/false
	- getAccessList(user,action): list of objects
	- getAuthorizedUsers(action,object): list of users

**Designate** is evaluated at specified Event; creates an [Involvement]()

**Assign** is evaluated at Start Event; creates an [Assignment]()

**Notify** is evaluated at specified Event; creates a [Notification]()


### AccessRules Internal Design
 
 - are define as Json file
 - are loaded with definition is loaded
 - are evaluated at the specified event
 - they add objects to the running instance
   - Assignment
   - Authorization
   - Involvement
   - Notification
 - If notification is immediate; is queued to be issued 
 - If notification is delay; it queued by Cron job

**Comment by ralphhanna** [comment]
Please give me your feedback on the above, I have mistakenly merge your changes in PR, not realizing the conflict between the two designs, I will work locally for the next few days till I becomes stable then will push.

Do you know how to incorporate the above design in the editor?

Thanks very much

**Comment by ralphhanna** [comment]
Assignment can also have a dueDate which can be a javascript function and priority

**Comment by kstan79** [comment]
Yes I aware this document but I not understand how it work and link to it previously. IMHO I feel that leverage from camunda modeller is easier approach cause building editor seems painful and redesign the wheel. 

However i respect your decision, I will try understand your initial design then get back to you afterward

**Comment by kstan79** [comment]
> Assignment can also have a dueDate which can be a javascript function and priority

Regarding this I have no experience on it.

**Comment by kstan79** [comment]
after some reading, I feel that using json to define rules outside bpmn flow chart seems defeat the purpose of bpmn and add difficulty to process designe and approve. I guess you intension is:
1. design separate json file allow developer to define suitable and flexible setting, and we no need to implement it in bpmn editor
2. have better programming overview without navigate ever node, one by one.
3. easier to program in overall, and easier to enhance too

IMHO,
1. Developer need to maintain 2 files, and management level required to evaluate 2 documents, and need manual effort to ensure 2 document compatible to each others. It also added complexity to handle error
2. as new comer the ideal is hard to understand, we will feel lose
3. to make bpmn and json work perfectly, we need to build separate editor link up both and that is nightmare
4. it is very custom design, i feel it will dead in one day. I recommend implementation compatible with camunda, activiti or etc. That is proven working well, and good for grow more community, since the bpmn diagram identical (i saw, we adobt camunda form, in this case we rather use back all their property.)

**Comment by ralphhanna** [comment]
I fully agree with you regarding keeping everything in bpmn file and using the editor.

**Comment by kstan79** [comment]
thanks, then shall we continue without using custom rule.json? You agree i use the assignee column for continue, and reserve authorization/notification for future, to bind with camunda modeler?

**Comment by ralphhanna** [comment]
Yes I agree, I am making all the required changes.

Thanks so much for your input

**Comment by ralphhanna** [comment]
See Release 1.4.0 [User Assignment](https://github.com/ralphhanna/bpmn-server/blob/master/docs/userAssignment.md)
