### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by jpgilchrist** [ralphhanna/bpmn-server#2]
Is there any particular reason ^8.0.0 is mandatory? I'm currently running 14.

**Comment by jpgilchrist** [comment]
As it stands, `yarn add bpmn-server --ignore-engines` bypasses the rule, but perhaps the engine rule should be changed if it's okay to run it on later versions of yarn.

**Comment by ralphhanna** [comment]
Thanks, fixed in new release
