### ISSUE TITLE
How to add a new feature

### ISSUE THREAD

**Issue by durbar** [ralphhanna/bpmn-server#22]
I want to add a new feature, say user authentication by username and password. I will be maintaining a new collection with user credentials in the mongodb. Now if I want to expose an API to do so, and handle the business logic behind it,  how to  approach that? 
Have tried adding a new route right under /restart at WebApp/routes/index.ts but was not able call it as it is throwing 404.

Please advice.
@ralphhanna

**Comment by ralphhanna** [comment]
Hi,

Adding authentications requires more work, a new release is coming in few weeks to support  user management. 

As for 404 error, did you compile your ts to generate a WebApp/routes/index.js ?

Thanks

**Comment by durbar** [comment]
Hey,
Thanks for the quick response. I got the the approach!
I was indeed not compiling the code.

Thanks,
Durbar Dasgupta
