### ISSUE TITLE
How to call external JS Script?

### ISSUE THREAD

**Issue by alecxs86** [ralphhanna/bpmn-server#26]
Hi,

Thank you for the great software package you put together,

I have been searching the forum and could not find any information in this regard. Is it possible for a Task defined in the modeller interface to call an external JS/NodeJS script ? As I see now it is possible to define only an inline script when setting the execution listener/input parameters/output parameters to type Script → Script Format JavaScript. But we would like for the activity to execute an external script.

Is there any possible way of doing this (without too much coding or a reasonable amount of coding) ?

Thank you

**Comment by ralphhanna** [comment]
Sorry for being so late, I just noticed it now.
The app is a node.js application this can be accomplished in many ways but require modification to appDelegate and can give you more guidance if still interested
