### ISSUE TITLE
NOT AN ISSUE! Guidance to handle an use case

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#33]
Hi,

First of all, thank you so much for this sophisticated BMN server with nice set of UIs and simple configuration. Beautifully done!

If I may ask, I need some guidance how to approach the below use case.
I'm planning to implement a workflow management tool with the following specs.

- I have around 10 different workflows (i.e., BPMN files) each one consisting of 10 to 15 different tasks; most of them are external microservices which needs to be called.
- Per day, I'll get around 70 to 100 workloads each of which should trigger one of the 10 workflows.
- Also need to track the states of the workflows and persist them for recovery and security 

I just started dabbling around BPMN engine a few days ago. No clue, how would I approach the above use case.
I'm sorry that if my question is too broad and has various aspects to it for consideration.

But any help would be greatly appreciated! Thank you so much.

**Comment by ralphhanna** [comment]
Hi,
1. Install BPMN Engine as per instructions
2. Edit configuration to point to your MongoDB database
3. Edit MyDelegate class to contain calls to your external microservices 
class MyAppDelegate extends DefaultAppDelegate{

    // for services that are not defined
    async serviceCalled(item) {

    }
    async service1(item) {
     ... your code here
    }
}
4. Define your processes and edit the bmp file to call the methods defined in step 3
    <bpmn:serviceTask id="serviceTask" name="Service Task" 
       implementation="service1">
    </bpmn:serviceTask>

the implementation parameter should be same as the method name

5.  Define your API to start various processes as per documentation
6.  Define your API to monitor processes

Keep in mind the BPMNServer takes care of persistence for you

Please let me know if you need further help

Thanks

**Comment by MaheshkumarSundaram** [comment]
Thank you so much for your quick response.

Steps 1 to 4 are crystal clear to me. But the steps 5 & 6 is where I don't have clear idea on how to do those.

Is there any example on how do carry out starting various processes and monitoring them in parallel? Or if you could explain a bit more on this, it would be great.

Sorry for the bothering.

**Comment by ralphhanna** [comment]
[example1.txt](https://github.com/ralphhanna/bpmn-server/files/9255711/example1.txt)
Attached is an example Typescript file to demonstrate starting a process and performing various queries against the MongoDB.

To run in parallel, you need to create a webservice. However, this will work fine as a separate processes since all operations are persistent.

If you like, I am working on a new release that supports webAPI in about a week.

Thanks

**Comment by MaheshkumarSundaram** [comment]
Hi,

Just a clarification. Approx. when would your next release be?

Thanks

**Comment by bpmn-ts** [comment]
very shortly, in the next 6 hours
Thanks

**Comment by MaheshkumarSundaram** [comment]
Awesome. Thank you!

**Comment by ralphhanna** [comment]
New Release 1.2.1 is now ready for testing.

Please see this file for more information about WebAPI
https://github.com/ralphhanna/bpmn-server/blob/master/docs/client-api.md
[https://opengraph.githubassets.com/2060ed346c558eec8837563c74894f541252d551614f566d7f3fb9ea699c4b2f/ralphhanna/bpmn-server]<https://github.com/ralphhanna/bpmn-server/blob/master/docs/client-api.md>
bpmn-server/client-api.md at master · ralphhanna/bpmn-server<https://github.com/ralphhanna/bpmn-server/blob/master/docs/client-api.md>
BPMN 2.0 server for Node.js , providing modeling, execution, persistence and monitoring for Workflow. along with sample UI. Intended to be developers workbench for BPMN 2.0 - bpmn-server/client-api...
github.com

________________________________

**Comment by ralphhanna** [comment]
Hi,

I have a question for you, how do you plan to handle User Tasks?

Please give me your feedback on this release.

Thanks,
Ralph
________________________________

**Comment by MaheshkumarSundaram** [comment]
Hi,

Thank you first of all.

>> how do you plan to handle User Tasks?

I am planning to integrate `bpmn-server` as a part of my web application which uses Sails for backend and React as frontend. For User tasks: My plan is use to forms at the frontend (`react-bootstrap` forms not the classic camunda form) & when the user completes the task via that form, signal the engine for completing the User Task.

I HAVEN'T TESTED THIS OR ANY OTHER THINGS SINCE I WAITING FOR YOUR NEW REALEASE. After your new release I'll test the engine's integration with my webapp. I would be able to provide a better feedback after that as I will test almost feature.

>> Please give me your feedback on this release.

Your server engine is perfect for worflow management. Persistence of the engine states is the one of the most vital features. Apart from that, I love the simplicity of the engine itself. it's not cluttered.

Personally, my webapp also uses MongDB as the core DB. `bpmn-server` using MongoDB is also a very nice advantage.

If I have to suggest any improvements, that would be documentation. It could be slightly better.
If any contribution is needed in that front, please feel free to reach out.  I would help in whatever ways I could.

Thank you!
