### ISSUE TITLE
Setting implementation property to ServiceTask programmatically or when modelling

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#36]
Hi,

I am aware currently one can't set the **implementation** property of the **Service Tasks** from the modeller.

Although there is a very good [properties panel](https://github.com/bpmn-io/bpmn-js-properties-panel) which can be integrated with modeler to configure additional properties to the tasks, the bpmn syntax for them is different like below:

```
<bpmn2:serviceTask id="Task_1" name="Task 1">
        <bpmn2:extensionElements>
          <camunda:properties>
            <camunda:property name="implementation" value="serviceTaskCall" />
          </camunda:properties>
        </bpmn2:extensionElements>
</bpmn2:serviceTask>
```

But `bpmn-server` expects the bpmn syntax to be like:

```
<bpmn2:serviceTask id="Task_1" name="Task 1" implementation="serviceTaskCall">
</bpmn2:serviceTask>
```

It would be advantageous if one could set the `implementation` property **when modelling or through programmatically while saving the bpmn file** instead of a user directly editing the bpmn file.

Could you recommend an efficient approach to achieve this? 
Thank you!

**Comment by bpmn-ts** [comment]
Thank you very much for your insightful feedback.
However, I have tested property-panel extension and it failed to save the
bpmn file correctly in some situations. In addition, the UI needs some
modifications to support bpmn-server extensions.

so you are 100% correct, it would be very nice to have that capabilities, I
can introduce some editor after the modelling process, while modelling
remains difficult at the moment, I will give it another try but will take
some time.

Thanks

**Comment by ralphhanna** [comment]
Release 1.3.0 now support property panel editor.
