### ISSUE TITLE
Complete User Task through API

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#37]
Hi,

Is it possible to complete a user task through API instead of using GUI?

I couldn't find any example on how to do this. Could you please provide an example?

Thank you!

**Comment by bpmn-ts** [comment]
Hi,

Sure you can using api/engine/invoke methods, also passing input data as
parameters

example in
https://github.com/ralphhanna/bpmn-server/blob/master/docs/examples/BuyCar-Remote.md

**Comment by MaheshkumarSundaram** [comment]
Ah sorry, I guess I missed that example. 
Thank you!

**Comment by ralphhanna** [comment]
Hi,

I have created this document for you to look at, it may help

https://github.com/ralphhanna/bpmn-server/blob/master/docs/customization.md

Thanks

**Comment by MaheshkumarSundaram** [comment]
Thank you @ralphhanna for your quick response
