### ISSUE TITLE
Process Modeller

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#38]
Hi,

The process modeller that comes with `bpmn-server` is handy and it's useful in storing the processes directly to DB without hassle.

Let's consider your example `Buy Used Car` process has some gateways and conditional expressions to regulate the sequential flow. But the inherent process modeller doesn't have features to configure expressions or properties. 
So, am I correct in understanding that you designed your processes using a different modeller not the inherent one?
If so, what utility/tool did you use to model all your processes along with configurations?

Thanks!

**Comment by bpmn-ts** [comment]
Hi,

I simply use Visual Studio or any text editor like Notepad++ to edit the
bpmn file, bpmn-server updates the database on next load.

Thanks

**Comment by MaheshkumarSundaram** [comment]
Ak okay. Thank you!

**Comment by ralphhanna** [comment]
I having some success with another try of Properties-Panel, should make it work within few days.

**Comment by MaheshkumarSundaram** [comment]
That would be great @ralphhanna. Hope it pans out well.
