### ISSUE TITLE
Guidance to handle an error scenario

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#40]
### Scenario:

1. `bpmn-server` is running separately
2. `bpmn-client` is running as a part of the main application
3. From the main app, I have to update the states of many running processes whenever required by the main application.

Currently I'm testing the above scenario using the following script which takes 3 required inputs for `invoke` from the user.
<details>
  <summary>Test Script</summary>

  ```js

  import { BPMNClient } from "bpmn-client";
import * as readline from 'readline';

const dotenv = require('dotenv');
const res = dotenv.config();

const cl = readline.createInterface( process.stdin, process.stdout );
const question = function(q) {
    return new Promise( (res, rej) => {
        cl.question( q, answer => {
            res(answer);
        })
    });
};

completeUserTask();

async function completeUserTask() {
    const server = new BPMNClient(process.env.HOST, process.env.PORT, process.env.API_KEY);

    const instanceId = await question('Please provide your Instance ID: ');
    const taskId = await question('Please provide your Task ID: ');
    let taskData = await question('Please provide your Task Data (json obj) if any: ');

    cl.close();

    if (taskData === ""){
        taskData = {};
    }else{
        taskData = JSON.parse(taskData.toString());
    }

    await server.engine.invoke(
        { id: instanceId, "items.elementId": taskId }
        , taskData);

    console.log("Completed UserTask:", taskId);
}
  ```
</details>

### Sample Process:
![image](https://user-images.githubusercontent.com/55505611/187440314-f363bf33-2fe2-4ebf-9caa-ac8ead84f8e3.png)

<details>
  <summary>BPMN File</summary>

  ```xml

 <?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1a44rne" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="9.3.2">
  <bpmn:process id="Process_0r2ybht" isExecutable="false">
    <bpmn:startEvent id="StartEvent_19yjmk7" name="Start">
      <bpmn:outgoing>Flow_1w74ars</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_1w74ars" sourceRef="StartEvent_19yjmk7" targetRef="Activity_1ji54p4" />
    <bpmn:userTask id="Activity_1ji54p4" name="Loading">
      <bpmn:incoming>Flow_1w74ars</bpmn:incoming>
      <bpmn:outgoing>Flow_1r48lhu</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:sequenceFlow id="Flow_1r48lhu" sourceRef="Activity_1ji54p4" targetRef="Activity_0qz0c0y" />
    <bpmn:sequenceFlow id="Flow_0yn3lbi" sourceRef="Activity_0qz0c0y" targetRef="Activity_1809f44" />
    <bpmn:serviceTask id="Activity_1809f44" name="AutoCheck" implementation="rtpAutoCheck">
      <bpmn:incoming>Flow_0yn3lbi</bpmn:incoming>
      <bpmn:outgoing>Flow_0rivcwh</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_0rivcwh" sourceRef="Activity_1809f44" targetRef="Gateway_1r8d4g2" />
    <bpmn:userTask id="Activity_131a198" name="Checking">
      <bpmn:incoming>Flow_11cwkoj</bpmn:incoming>
      <bpmn:outgoing>Flow_0qwuw2x</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:exclusiveGateway id="Gateway_0id7guv">
      <bpmn:incoming>Flow_0qwuw2x</bpmn:incoming>
      <bpmn:outgoing>Flow_1b6byb4</bpmn:outgoing>
      <bpmn:outgoing>Flow_0bojcgd</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:sequenceFlow id="Flow_0qwuw2x" sourceRef="Activity_131a198" targetRef="Gateway_0id7guv" />
    <bpmn:sequenceFlow id="Flow_1b6byb4" name="CheckPass" sourceRef="Gateway_0id7guv" targetRef="Activity_0va5u0o">
      <bpmn:conditionExpression xsi:type="bpmn:tExpression"><![CDATA[(this.checkStatus === "Pass")]]></bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:serviceTask id="Activity_0va5u0o" name="Generate Text File" implementation="rtpGenerateFile">
      <bpmn:incoming>Flow_1b6byb4</bpmn:incoming>
      <bpmn:outgoing>Flow_0bz5tod</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_0bojcgd" name="CheckFail" sourceRef="Gateway_0id7guv" targetRef="Activity_0qz0c0y">
      <bpmn:conditionExpression xsi:type="bpmn:tExpression"><![CDATA[(this.checkStatus === "Fail")]]></bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:exclusiveGateway id="Gateway_1r8d4g2">
      <bpmn:incoming>Flow_0rivcwh</bpmn:incoming>
      <bpmn:outgoing>Flow_11cwkoj</bpmn:outgoing>
      <bpmn:outgoing>Flow_0qwl78t</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:sequenceFlow id="Flow_11cwkoj" name="AutoCheckPass" sourceRef="Gateway_1r8d4g2" targetRef="Activity_131a198">
      <bpmn:conditionExpression xsi:type="bpmn:tExpression"><![CDATA[(this.autoCheckStatus === "Pass")]]></bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:sequenceFlow id="Flow_0qwl78t" name="AutoCheckFail" sourceRef="Gateway_1r8d4g2" targetRef="Activity_0qz0c0y">
      <bpmn:conditionExpression xsi:type="bpmn:tExpression"><![CDATA[(this.autoCheckStatus === "Fail")]]></bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:userTask id="Activity_0qz0c0y" name="Planning">
      <bpmn:incoming>Flow_1r48lhu</bpmn:incoming>
      <bpmn:incoming>Flow_0bojcgd</bpmn:incoming>
      <bpmn:incoming>Flow_0qwl78t</bpmn:incoming>
      <bpmn:outgoing>Flow_0yn3lbi</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:endEvent id="Event_0wlem5q" name="End">
      <bpmn:incoming>Flow_0bz5tod</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0bz5tod" sourceRef="Activity_0va5u0o" targetRef="Event_0wlem5q" />
  </bpmn:process>
  ```
</details>

This is just an example. My actual use case is complex with around 30 elements.

### Issue:

I have been using the above test script to complete the user tasks in the above example handling different inputs for the gateways.
At some point, I received this error:

```shell
*** ERROR *** task id not valid

Error Message: *** ERROR *** task id not valid

Stacktrace:
====================
Error: *** ERROR *** task id not valid
    at Logger.error (F:\Programming\Test-BPMN-Server-125\node_modules\bpmn-server\src\common\Logger.js:66:15)
    at Execution.<anonymous> (F:\Programming\Test-BPMN-Server-125\node_modules\bpmn-server\src\engine\Execution.js:216:33)
    at Generator.next (<anonymous>)
    at fulfilled (F:\Programming\Test-BPMN-Server-125\node_modules\bpmn-server\src\engine\Execution.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: *** ERROR *** task id not valid
    at Logger.error (F:\Programming\Test-BPMN-Server-125\node_modules\bpmn-server\src\common\Logger.js:66:15)
    at Execution.<anonymous> (F:\Programming\Test-BPMN-Server-125\node_modules\bpmn-server\src\engine\Execution.js:216:33)
    at Generator.next (<anonymous>)
    at fulfilled (F:\Programming\Test-BPMN-Server-125\node_modules\bpmn-server\src\engine\Execution.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Error: *** ERROR *** task id not valid
(node:6780) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 all listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```
Increasing the listeners doesn't seem to be a wise solution for this scenario. Am I right?
What am I doing wrong and how to handle such scenario without effecting the performance?

Any help would be appreciated. Thank you!

**Comment by bpmn-ts** [comment]
Hi,

I am not sure of how do you get the instanceId? InstanceId is system
assigned.

This example details how to capture InstanceId

https://github.com/ralphhanna/bpmn-server/blob/master/docs/examples/BuyCar-Remote.md

I just don't see the code to start the processes

Or you can just perform findItems instead to see all outstanding items

 var items= await
getServer().datastore.findInstances({'items.elementId'='Approve','items.status'='wait'});
or
 var items= await
getServer().datastore.findInstances({'items.status'='wait'});

To further help, can you please upload your process to bpmn.omniworkflow.ocm

Thanks,

**Comment by ralphhanna** [comment]
Ok, I have expanded your program to include more features:

Below is the new code:
```js
//import { BPMNClient } from "bpmn-client";
import { BPMNClient } from './';

import * as readline from 'readline';

const dotenv = require('dotenv');
const res = dotenv.config();

const server = new BPMNClient(process.env.HOST, process.env.PORT, process.env.API_KEY);

const cl = readline.createInterface( process.stdin, process.stdout );
const question = function(q) {
  return new Promise( (res, rej) => {
      cl.question( q, answer => {
          res(answer);
      })
  });
};

completeUserTask();

async function completeUserTask() {
	console.log('Commands:');
	console.log('	q	to quit');
	console.log('	s	start process ');
	console.log('	lo	list outstanding items');
	console.log('	l	list instances for a process');
	console.log('	di	display Instance information');
	console.log('	i	invoke item');
	
  let option='';
  var command;
  while(option!=='q')
  {
	command= await question('Enter Command, q to quit\n\r>');
	let opts=command.split(' ');
	option=opts[0];
	switch(option)
	{
		case 'lo':
			console.log("list outstanding items");
			await findItems({ "items.status": "wait"});
			break;
		case 'l':
			console.log("list instances");
			await listInstances();
			break;
		case 'di':
			console.log("displaying ");
			await displayInstance();
			break;
		case 'i':
			console.log("invoking");
			await invoke();
			break;
			
		case 's':
			console.log("starting");
			await start();
			break;
		
	}
  
  }


  console.log("bye");
 
  cl.close();

}
async function start()
{
  const name = await question('Please provide your process name: ');
  let taskData = await question('Please provide your Task Data (json obj) if any: ');

  if (taskData === ""){
      taskData = {};
  }else{
      taskData = JSON.parse(taskData.toString());
  }
  
  let response=await server.engine.start(name, taskData);

  console.log("Process "+name+" started:", response.items,'InstanceId',response.id);
}
async function findItems(query) {
	var items = await server.datastore.findItems(query);

	console.log(items);
	for (var i = 0; i < items.length; i++) {
		let item = items[i];
		console.log(`${item.name} - ${item.elementId}	instanceId:	${item['instanceId']}`);
	}

}
async function listInstances() {
	const name = await question('Please provide your process name: ');

	let insts = await server.datastore.findInstances({ name: name})

	for (var i = 0; i < insts.length; i++) {
		let inst = insts[i];
		console.log(`name: ${inst.name} status: ${inst.status}	instanceId:	${inst.id}
	startedAt: ${inst.startedAt} endedAt ${inst.endedAt}`, 'data:', inst.data);
	}
}

async function displayInstance() {
	const instanceId = await question('Please provide your Instance ID: ');

	let insts = await server.datastore.findInstances({id: instanceId})

	for (var i = 0; i < insts.length; i++) {
		let inst = insts[i];
		var items = inst.items;
		console.log(`name: ${inst.name} status: ${inst.status}	instanceId:	${inst.id}
	startedAt: ${inst.startedAt} endedAt ${inst.endedAt}`,'data:', inst.data);
		for (var j = 0; j < items.length; j++) {
			let item= items[j];
			console.log(`element: ${item.elementId} status: ${item.status}	id:	${item.id}`);
		}
	}
}
async function invoke()
{
  const instanceId = await question('Please provide your Instance ID: ');
  const taskId = await question('Please provide your Task ID: ');
  let taskData = await question('Please provide your Task Data (json obj) if any: ');

  if (taskData === ""){
      taskData = {};
  }else{
      taskData = JSON.parse(taskData.toString());
  }
  
 let response=await server.engine.invoke(
      { id: instanceId, "items.elementId": taskId }
      , taskData);

  console.log("Completed UserTask:", taskId,response.items);
}
```
Here is a sample output:


Commands:
        q       to quit
        s       start process
        lo      list outstanding items
        l       list instances for a process
        di      display Instance information
        i       invoke item
Enter Command, q to quit
**>s**
s
starting
Please provide your process name: test4
test4
Please provide your Task Data (json obj) if any:

**Process test4 started: [**
  {
    id: 'd1ea33bb-8e9d-4780-999e-80b61e60f3ca',
    seq: 0,
    tokenId: 0,
    elementId: 'StartEvent_19yjmk7',
    name: 'Start',
    status: 'end',
    startedAt: '2022-08-31T03:06:01.395Z',
    endedAt: '2022-08-31T03:06:01.397Z',
    type: 'bpmn:StartEvent',
    assignments: [],
    authorizations: [],
    notifications: []
  },
  {
    id: 'e693ea0d-430c-4d61-9182-dd9c2af2329e',
    seq: 1,
    tokenId: 0,
    elementId: 'Flow_1w74ars',
    status: 'end',
    endedAt: null,
    type: 'bpmn:SequenceFlow',
    assignments: [],
    authorizations: [],
    notifications: []
  },
  {
    id: 'b438a3c0-ba23-433b-a664-8903d2a35a0c',
    seq: 2,
    tokenId: 0,
    elementId: 'Activity_1ji54p4',
    name: 'Loading',
    status: 'wait',
    startedAt: '2022-08-31T03:06:01.428Z',
    endedAt: null,
    type: 'bpmn:UserTask',
    assignments: [],
    authorizations: [],
    notifications: []
  }
] InstanceId b2a41e29-7104-4699-a11a-303b7b4fc9be
Enter Command, q to quit
**>i**
i
invoking
Please provide your Instance ID: b2a41e29-7104-4699-a11a-303b7b4fc9be
b2a41e29-7104-4699-a11a-303b7b4fc9be
Please provide your Task ID: Activity_1ji54p4
Activity_1ji54p4
Please provide your Task Data (json obj) if any:

**Completed UserTask: Activity_1ji54p4 [**
  {
    id: 'd1ea33bb-8e9d-4780-999e-80b61e60f3ca',
    seq: 0,
    tokenId: 0,
    elementId: 'StartEvent_19yjmk7',
    name: 'Start',
    status: 'end',
    startedAt: '2022-08-31T03:06:01.395Z',
    endedAt: '2022-08-31T03:06:01.397Z',
    type: 'bpmn:StartEvent',
    assignments: [],
    authorizations: [],
    notifications: []
  },
  {
    id: 'e693ea0d-430c-4d61-9182-dd9c2af2329e',
    seq: 1,
    tokenId: 0,
    elementId: 'Flow_1w74ars',
    status: 'end',
    endedAt: null,
    type: 'bpmn:SequenceFlow',
    assignments: [],
    authorizations: [],
    notifications: []
  },
  {
    id: 'b438a3c0-ba23-433b-a664-8903d2a35a0c',
    seq: 2,
    tokenId: 0,
    elementId: 'Activity_1ji54p4',
    name: 'Loading',
    status: 'end',
    startedAt: '2022-08-31T03:06:01.428Z',
    endedAt: '2022-08-31T03:06:42.833Z',
    type: 'bpmn:UserTask',
    assignments: [],
    authorizations: [],
    notifications: []
  },
  {
    id: 'bce5f1cf-93d2-4da8-aefa-36d5eeb87abf',
    seq: 3,
    tokenId: 0,
    elementId: 'Flow_1r48lhu',
    status: 'end',
    endedAt: null,
    type: 'bpmn:SequenceFlow',
    assignments: [],
    authorizations: [],
    notifications: []
  },
  {
    id: '1c3be5c2-58f6-47d8-8254-e0eac92bff4c',
    seq: 4,
    tokenId: 0,
    elementId: 'Activity_0qz0c0y',
    name: 'Planning',
    status: 'wait',
    startedAt: '2022-08-31T03:06:42.848Z',
    endedAt: null,
    type: 'bpmn:UserTask',
    assignments: [],
    authorizations: [],
    notifications: []
  }
]
Enter Command, q to quit
>
```

**Comment by ralphhanna** [comment]
The error message you are getting is simply saying the element you are trying to invoke either does not exist or is already completed, no need to increase listeners.
Here is an example:


Error: Error: *** ERROR *** task id not valid
Invoking task failed for: Activity_1ji54p4 b2a41e29-7104-4699-a11a-303b7b4fc9be
[
  {
    id: 'b438a3c0-ba23-433b-a664-8903d2a35a0c',
    seq: 2,
    itemKey: null,
    tokenId: 0,
    elementId: 'Activity_1ji54p4',
    name: 'Loading',
    status: 'end',
    userId: null,
    startedAt: '2022-08-31T03:06:01.428Z',
    endedAt: '2022-08-31T03:06:42.833Z',
    type: 'bpmn:UserTask',
    timeDue: null,
    data: {},
    messageId: null,
    signalId: null,
    assignments: [],
    authorizations: [],
    notifications: [],
    processName: 'test4',
    instanceId: 'b2a41e29-7104-4699-a11a-303b7b4fc9be'
  }
]
Loading - Activity_1ji54p4      instanceId:     b2a41e29-7104-4699-a11a-303b7b4fc9be
Enter Command, q to quit

**Comment by MaheshkumarSundaram** [comment]
Thank you so much for the detailed explanation @ralphhanna. Very much appreciated!
