### ISSUE TITLE
Clarification regarding configuring service task

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#41]
_Using version 1.3.1_

Hi,

First of all, thank you so much for the new release with `BPMN-Properties-Panel`. It's an excellent addition.
I am almost at the end of testing phase to integrate `bpmn-server` in our project. I simply adore this node based server engine. It saved me a great deal of effort for our project. Thank you so much for your excellent contribution @ralphhanna. Greatly appreciated!

I have a clarification regarding the service task configuration.
Is configuring `implementation` through properties panel (like below) not enough?

![image](https://user-images.githubusercontent.com/55505611/187640160-3f7d6f65-26fd-456f-8f4e-2ac01ab62b1c.png)

Do I also have to edit the BPMN directly to add `implementation` property for service tasks!? It seems to be this case.
Is it supposed to be this way? It's just that all other configurations could be done through the panel except this. Seems like an odd one out.

Thanks!

**Comment by ralphhanna** [comment]
Thanks for finding out this bug, property panel uses camunda:delegateExpression
is now fixed in release 1.3.3

**Comment by MaheshkumarSundaram** [comment]
I did a fresh install and tested this. Although the property `camunda:delegateExpression` is set through modeller, it seems `implementation` property is still needed to carry out service tasks.
Could you kindly look into this?

Thanks
