### ISSUE TITLE
Significance of running engines after processes end

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#42]
Hi,

I could see that there are running engines in the Workbench UI after the processes end.
If I start processes, after their end events; I suppose there should no running engines right? 
But I still see two running instances (in case of 2 processes) after their end events.

Could you please explain the significance behind this?

Aside from the above question, is the `data.caseId` unique across all instances?

Thanks!

**Comment by ralphhanna** [comment]
There is no real impact other than memory, and no real value of keeping them.

Therefore, in release 1.3.3 it removes completed engines.
