### ISSUE TITLE
Discrepancy with `findItems`

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#43]
Consider the below example in its current state.

### Current state of the running instance:
![image](https://user-images.githubusercontent.com/55505611/187673065-19e45354-2efb-467a-aba6-85206832e17c.png)

### Issue:

I tried to find the items using `findItems`:

```js
var findRes = await server.datastore.findItems({ id: instanceId, "items.elementId": taskId});
console.log("Find Result:", findRes);
```
Sample Input for the `findItems` query:
```js
let instanceId = "a929dce1-67a7-4a15-8ff7-fd4bbff24b07";
let taskId = "planning_task";
```

Sample Output for the `findItems` query:
```shell
Find Result: [
  {
    id: '082ae8db-f315-42d2-b5d8-2a41b61df6a6',
    seq: 4,
    itemKey: null,
    tokenId: 0,
    elementId: 'planning_task',
    name: 'Planning',
    status: 'end',
    userId: 'demoUser',
    startedAt: '2022-08-31T11:47:27.761Z',
    endedAt: '2022-08-31T11:47:29.861Z',
    type: 'bpmn:UserTask',
    timeDue: null,
    data: { caseId: 5656, autoCheckStatus: 'Pass', checkStatus: 'Fail' },
    messageId: null,
    signalId: null,
    assignments: [],
    authorizations: [],
    notifications: [],
    processName: 'RTPWorkflowSample',
    instanceId: 'a929dce1-67a7-4a15-8ff7-fd4bbff24b07'
  }
]
```

For the above scenario, I expected that `findItems` would display three items in the list instead of one.

### Expected Behaviour:
`findItems` would retrieve all the items in the instance based on the query. It would narrow down to one or few items only when the query consists of other conditions.

**Comment by ralphhanna** [comment]
Fixed in Release 1.3.3
Apparently, MongoDB $elematch works differently in projection, it only retrieves the first element that match the condition.
