### ISSUE TITLE
Release 1.3.3

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#45]
I see that [ `bpmn-server`](https://www.npmjs.com/package/bpmn-server) at npm has the latest version of `v1.3.3`.
In here, I only see `v1.3.2` in the commits. 

Is `v1.3.3` yet to be released? 
Because I did a fresh install and the issues #41 & #42 still exist in that. Sorry, I'm just wondering!

Aside from the above question, is there any near plan for user authentication via login mechanism?

Thanks!

**Comment by ralphhanna** [comment]
Sorry, I have missed the push.

is done now, thanks.
as for authentication, I am working on this, using passport! any other ideas are welcomed.

Thanks

**Comment by MaheshkumarSundaram** [comment]
Thank you!

**Comment by MaheshkumarSundaram** [comment]
@ralphhanna if you need any help in developing any of the new features, I would be glad to offer my contributions in whatever ways I could. `bpmn-server` is such a helpful engine. Please feel free to reach out.

**Comment by ralphhanna** [comment]
Thank you very much, I would surely appreciate any participation.
Feel free to browse the project for upcoming tasks, or do a pull request and improve docs.

you can reach me @ ralphhanna at hotmail dot com 
Thanks very much
