### ISSUE TITLE
`messageMatchingKey` when throwing messages & `id` config

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#47]
### 1:
What's the importance of `messageMatchingKey` when throwing or catching message events? Does the message event won't work without this?

In the doc, I can see that you have mentioned 
>> However, the challenge here is that make sure the message is sent to the specific instance, that is where the Matching key is used

Is the `messageRef` (Message Id) not sufficient enough to target the specific instance?

### 2:
One issue when using modeller,
For `signal` and `message` events, we generally use the same `id` (`signalRef` or `messageRef` in BPMN) for the throw and catch events.
The message/signal `id` is not editable. We can add  a new one or choose from a list but there is no option to edit.
This is not a problem when configuring `id`s in one process or its sub processes.
But it becomes a problem, when I want to use the same `id` for a separate processes (different BPMN file). In such case, I manually  edited the BPMN files for the `id`s to match.

In your example processes, `msgThrow` and `MsgCatch`, I see that you have matching `id`s; how did you configure them without having to edit the file directly.

Thanks!

**Comment by ralphhanna** [comment]
1. A Message can only be caught once if it has a matching MsgId, MsgId is defined at the process level.
However, when you have several instances from the same process, all having the same MsgId, which instance should catch the message? This is where the MessageKey is used. Not only it locates an instance with the MsgId but also with appropriate key (say caseId)
3. No need to edit files; in property panel, 
- click + to create new msg Id
- from drop down select the msg you like

**Comment by ralphhanna** [comment]
I am sorry for not being very clear.

It is the **Message Name** that matters not the Message Id, you can edit the Message Name in both processes so they match.
Thanks

![image](https://user-images.githubusercontent.com/11893416/188031187-17961066-0206-49a3-824e-a3aadb0ac7b0.png)

**Comment by MaheshkumarSundaram** [comment]
Ah sorry. That clears everything. Thank you!
