### ISSUE TITLE
Returning data from script task

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#48]
How do I return data from a script task as the output?

In the properties panel, not sure how to utilize the `Result Variable` for script task?

Thanks!

**Comment by ralphhanna** [comment]
bpmn-server does not use Result Variable, but uses input/output.

For script tasks, no need to input/output parameters, even though they work,
you can simply set data object inside the script.

```js
  data['reminderCounter']=5;
```

**Comment by MaheshkumarSundaram** [comment]
Thank you!
