### ISSUE TITLE
Properties Panel `Name` field not editable

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#54]
**_Using 1.3.6_**

`Name` field of any element is not editable anymore in the properties panel itself.
Although it can be edited from the modeller canvas directly.

Thanks!

**Comment by ralphhanna** [comment]
Yes, Name , Type and Cardinality (loop type) are not editable in Properties Panel.

I believe it was always like this, since they are editable in canvas.

This is not a bug, but by design.

Thanks

**Comment by MaheshkumarSundaram** [comment]
I have edited those before using Properties Panel in previous versions.

So, I was just wondering.

**Comment by bpmn-ts** [comment]
using bpmn-server or another product? which version was it?
Thanks

**Comment by MaheshkumarSundaram** [comment]
Issue is in `1.3.7`
