### ISSUE TITLE
`data` in `items` array - MongoDB

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#57]
**_Using 1.3.7_**

**Please note, the case mentioned below doesn't seem to affect the functionality or the execution process of the instances.**

In the `items` array of the instances in the DB, the value of `data` is always `null`.

For example, consider the example process `Hungry`, after the execution of the user task `choose recipe`, the data is saved in the main `data` object of the DB. No issue in that.
But I believed that would also be the case with the `data` inside the `items` array which is not the case.

![image](https://user-images.githubusercontent.com/55505611/188888589-a82601ce-84c3-4c9d-a465-f1bc616ccd16.png)

Although it doesn't have any significance towards the execution of the instance, just thought to bring this to notice.

Thanks!

**Comment by ralphhanna** [comment]
Yes, thanks
data is saved at the instance level for query purposes, but has a getter property at the item level

**Comment by MaheshkumarSundaram** [comment]
I understand that. But the getter property of `data` is always `null` instead of the data objects. Shouldn't it contain the data object existing at the certain point?
