### ISSUE TITLE
Running Instances after restart or shutdown

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#59]
Hi @ralphhanna,

Persistence of the instances are handled well. There is no problem in that.

The concern is this: Suppose if the engine shutdowns due to an external problem while there are some running instances, the states will be saved. But those running instances are not running anymore after the restart (I mean they don't auto-resume from where they were left). It seems one has to manually intervene to resume them. 

Could this be rectified so that the engine will auto-resume their running instances from the saved state after restart or unexpected shutdown?

Thanks!

**Comment by ralphhanna** [comment]
You are right, it would be nice to auto-resume running instances, however, there is a risk of re-executing activities that already started that may cause some harm.

The best we hope for at this stage is identify running instances and allow an admin to resume them or control what to do, this is another point of discussion and exploration.
Thanks
