### ISSUE TITLE
Rebuilding processes from client side

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#73]
Hi @ralphhanna,

Is there a way to rebuild processes without having to restart the server itself?

Suppose I am writing a new BPMN file to the `processes` folder externally not through your web app, I would like to rebuild the processes without having to restart the server itself.

Is it possible to trigger the rebuild from `bpmn-client` API? If not, it would be convenient to have this feature,

Thanks.

**Comment by ralphhanna** [comment]
Hi,

At the moment, you have to run a script at the server similar to this:
```js
import  { configuration }   from './';
import { BPMNServer, Logger } from './';

const server = new BPMNServer(configuration);

const model = 'test1';

server.definitions.rebuild(model);

```
You can add a monitor process to watch for changes and perform rebuild above.

What would be the scenario that will have a client rebuild a process? would it be better to have the client upload (save) the bpmn file?

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna ,

>> What would be the scenario that will have a client rebuild a process? would it be better to have the client upload (save) the bpmn file?

Yes it would be better if the BPMN file can be saved (uploaded) through the `bpmn-client` API. But I don't see any viable methods in the [client API](https://github.com/ralphhanna/bpmn-server/blob/master/docs/client-api.md). Am I missing something?

Thanks!

**Comment by ralphhanna** [comment]
Will add in a new release.
Thanks

**Comment by MaheshkumarSundaram** [comment]
> Will add in a new release. Thanks

Hi @ralphhanna,
Could you please let me know when is this new release scheduled?

**Comment by bpmn-ts** [comment]
Sorry for the delay, by early next week, hope over the weekend.

Thanks

**Comment by ralphhanna** [comment]
New Release 1.3.15 now supports the following API additions:
- definitions/import
- definitions/delete
- definitions/rename

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna ,

Could you please update [`bpmn-client`](https://github.com/ralphhanna/bpmn-client) to adapt these changes too?
Thanks!

**Comment by ralphhanna** [comment]
done, thanks

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna,

In the updated release, I see that the `definitions.import` requires a `filepath`. 
Could you please include an option to feed either a `filepath` or direct `xml` content of BPMN file to make it more flexible? 

Thanks!

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna,

In the updated release, I see that the definitions.import requires a filepath.
Could you please include an option to feed either a filepath or direct xml content of BPMN file to make it more flexible?

Thanks!
