### ISSUE TITLE
Upgrading Properties Panel to use Form as a Camunda Form instead of Form Key only

### ISSUE THREAD

**Issue by tamlongdo** [ralphhanna/bpmn-server#78]
Hi @ralphhanna ,

I would like to upgrade the Property Panel to a newer version to use Camunda Form Configuration, like this:
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/7964353/216063839-1ff4968f-97ab-4e5a-a206-fbca03856d34.png">

How could I upgrade the Property Panel to a newer version?
In case it couldn't, How could I customize the Form tab to use the external form? - because I checked and see the file: modeller-withPropertyPanel.js is bundled and difficult to customize.

Could you please give me some advice?
My version is 1.3.9
Thanks.

**Comment by ralphhanna** [comment]
May consider in a feature release
