### ISSUE TITLE
Request to update dependencies

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#79]
Hi @ralphhanna,

This is a request. Since the dependencies' versions varies a lot as of now, `npm i` shows some vulnerabilties. Could I kindly request you to update those? 

I could update them locally but not sure what would I break if I do. Thought it would be better coming from you.

Thank you!

**Comment by ralphhanna** [comment]
Fixed in Release 1.3.18
