### ISSUE TITLE
Issue with Interrupting Timer Boundary Event

### ISSUE THREAD

**Issue by SundaramMaheshkumar** [ralphhanna/bpmn-server#84]
Hi @ralphhanna,

![image](https://user-images.githubusercontent.com/118889895/230330223-943f2384-9e36-4ca8-9731-121848e5e8c5.png)

An interrupting timer boundary event should interrupt it's main event and proceed the pathway after the timeout right? Here, it just ends the workflow outright instead of proceeding.

Could you please look into this?

Thanks

**Comment by bpmn-ts** [comment]
You need to add an action to be taken when the timer fires see example
below:

[image: image.png]

**Comment by SundaramMaheshkumar** [comment]
I added action to the timer:

![image](https://user-images.githubusercontent.com/118889895/231100468-5dd21167-525c-4a03-9ca1-3e676b04bb21.png)

Still it doesn't work as expected

**Comment by ralphhanna** [comment]
Fixed in Releae 1.3.18
