### ISSUE TITLE
Exclusive Gateway Convergence

### ISSUE THREAD

**Issue by SundaramMaheshkumar** [ralphhanna/bpmn-server#87]
Hi @ralphhanna ,

Exclusive Gateway Convergence example:

Workflow Name: `test-exclusive-gateway` in https://bpmn.omniworkflow.com/

![image](https://user-images.githubusercontent.com/118889895/232708231-738ba942-7798-4def-a747-e1435a7e9efe.png)

I expect the exclusive gateway to proceed when one of the incoming flow is complete instead it's also waiting for the other flow to complete as well. Isn't this the behaviour of parallel gateway!?

Also if the flow is progressed because of `UT2`, there is also a question of what should happen to the other task `UT1`? Should it get terminated ? 

Converging exclusive gateway's behaviour is really confusing for me. :confused: 

Kindly look into this. Thanks.

**Comment by ralphhanna** [comment]
Hi,
You have a point there, but the question is what to do with the other outstanding task UT1 ? I think it should be cancelled.

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna 

>>You have a point there, but the question is what to do with the other outstanding task UT1 ? I think it should be cancelled.

Yeah I think the other task would be cancelled too.

**Comment by ralphhanna** [comment]
As I demonstrated above, this works fine if both Gateways are "Exclusive"
Can you please provide a good example where a "Parrallel Gateway" is required instead of "Exclusive Gateway"

**Comment by ralphhanna** [comment]
Fixed in Release 1.3.21
