### ISSUE TITLE
Issue  with `vars` in items

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#89]
Hi @ralphhanna 

I have a workflow like below, 
![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/f3592bd1-d6e2-423c-8af3-f0de59b7cc7f)

There is a receive task which has an input parameter.

Now, I have a running instance for the above workflow which is waiting at the Receive task:

![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/883ad5e4-86a6-4b4d-b225-32d405aef5a8)

But the `vars` is empty, when I use `server.datastore.findItems({
        'items.status': 'wait',
        'items.type': 'bpmn:ReceiveTask',
    })`

![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/6b2067e2-dc70-4f35-a64c-6a656d065bff)

Could you please look into this? Thanks

**Comment by ralphhanna** [comment]
Please make sure that you have set the item.vars inside the service or as event script.

item.vars is not automatically set to input, just in case your input is too large or you like to store other data like output.

Thanks

**Comment by bpmn-ts** [comment]
Using an event listener as in the example
[image: image.png]

Thanks

**Comment by MaheshkumarSundaram** [comment]
@ralphhanna,

[**Issue**](https://github.com/ralphhanna/bpmn-client/issues/26): Could you please add vars to the interface DataObjects.ts in `bpmn-client`?

Thanks.
